class ParserException(Exception): ...
class ExpectedTokenError(ParserException): ...
class SyntaxError(ParserException): ...

class TypeCheckerException(Exception): ...
class MismatchedTypesError(TypeCheckerException): ...
class TypeNotFoundError(TypeCheckerException): ...
class CouldntInferTypeError(TypeCheckerException): ...
class BranchMismatchError(TypeCheckerException): ...

class CompilerException(Exception): ...
class LookupError(CompilerException): ...
class FieldMismatchError(CompilerException): ...
class ValueResolverError(CompilerException): ...
class TypeMismatchError(CompilerException): ...