class CompilerException(Exception): ...
class LookupError(CompilerException): ...
class FieldMismatchError(CompilerException): ...
class ValueResolverError(CompilerException): ...
class TypeMismatchError(CompilerException): ...