class ParserException(Exception): ...
class ExpectedTokenError(ParserException): ...
class SyntaxError(ParserException): ...
class MissingPrefixParseFunction(ParserException): ...
class LiteralParseError(ParserException): ...

class TypeCheckerException(Exception): ...
class MismatchedTypesError(TypeCheckerException): ...
class TypeNotFoundError(TypeCheckerException): ...
class FunctionNotFoundError(TypeCheckerException): ...
class VariableNotFoundError(TypeCheckerException): ...
class CouldntInferTypeError(TypeCheckerException): ...
class BranchMismatchError(TypeCheckerException): ...
class IncorrectArgumentCountError(TypeCheckerException): ...

class CompilerException(Exception): ...
class LookupError(CompilerException): ...
class FieldMismatchError(CompilerException): ...
class ValueResolverError(CompilerException): ...
class TypeMismatchError(CompilerException): ...
class ReassignConstError(CompilerException): ...