"""
This type stub file was generated by pyright.
"""

from llvmlite import ir


class Context:
    def __init__(self) -> None:
        ...
    
    def get_identified_type(self, name: str, packed=...) -> ir.IdentifiedStructType:
        ...
    


global_context: Context = ...
